def tags():
    return [
        'Adhoc',
        'Binary Search',
        'Bitmask',
        'Brute Force',
        'Constructive Algorithms',
        'Data Structures',
        'Divide and Conquer',
        'Dynamic Programming',
        'Explicitly Excluded (from IOI)',
        'Graph Theory',
        'Greedy',
#        'Implementation Cancer',
        'Information Theory',
        'Joke',
        'Line Sweep/Sliding Window',
        'Math',
        'Meet in the Middle', 
        'Slope Trick',
        'Square Root Decomposition',
        'Syntax',
        'Trees',
    ]
